# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a70de1ebf6fe6a351a764d4671a13975"
name = "productmanagement-app"
handle = "productmanagement-app"
application_url = "https://jokes-filled-outdoors-portrait.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-d11de8e5.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://jokes-filled-outdoors-portrait.trycloudflare.com/auth/callback",
  "https://jokes-filled-outdoors-portrait.trycloudflare.com/auth/shopify/callback",
  "https://jokes-filled-outdoors-portrait.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
